### ISSUE TITLE
:art: Improvement: Reuse Supabase CreateClient Instance

### ISSUE THREAD

**Issue by mcnaveen** [timelessco/recollect#35]
### Bug Report Checklist

- [x] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/timelessco/bookmark-tags/issues?q=is%3Aissue) and found none that matched my issue.

## What is the issue?
Supabase `create client` is being created on each API endpoint. Which creates a code duplication.

```ts
const supabase = createClient(
	process.env.NEXT_PUBLIC_SUPABASE_URL,
	process.env.SUPABASE_SERVICE_KEY,
);
```

Here are a few references to code duplication.
https://github.com/timelessco/bookmark-tags/blob/b6516524f9c5b32e1fa92910bfce998f26418ef9/src/pages/api/tags/add-tag-to-bookmark.ts#L40
https://github.com/timelessco/bookmark-tags/blob/b6516524f9c5b32e1fa92910bfce998f26418ef9/src/pages/api/tags/create-user-tags.ts#L40
https://github.com/timelessco/bookmark-tags/blob/b6516524f9c5b32e1fa92910bfce998f26418ef9/src/pages/api/bookmark/add-bookmark-min-data.ts#L46

## Resolution
- Instead. Initialize it once under the `lib/` directory and export the supabase client for usage.

**Comment by abhishekmg** [comment]
This has been worked on the createClient can now only be found in `supabaseServerClient.ts` file

closing the issue
